### ISSUE TITLE
Start up error

### ISSUE THREAD

**Issue by cooger009** [AmanRathoreP/Anki-Addon-for-Multiple-Decks-Creation#1]
![multi deck creation](https://github.com/AmanRathoreP/Anki-Addon-for-Multiple-Decks-Creation/assets/133258508/9b0e4ca2-1708-48cf-a2c5-ce346a6e623e)

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.62 (77dd1dc1) Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-05-11 02:11:00

Caught exception:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\461193445\main.py", line 17, in create_multiple_decks
    info = show_custom_dialog()
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\461193445\main.py", line 10, in show_custom_dialog
    dialog = my_user_interactive_GUI.MyCustomDialog(mw)
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\461193445\src\my_user_interactive_GUI.py", line 176, in __init__
    file_widget = FileWidget()
  File "C:\Users\User\AppData\Roaming\Anki2\addons21\461193445\src\my_user_interactive_GUI.py", line 41, in __init__
    self.file_list.setSelectionMode(QListWidget.ExtendedSelection)
AttributeError: type object 'QListWidget' has no attribute 'ExtendedSelection'
[](url)

**Comment by AmanRathoreP** [comment]
I was a bit occupied into lots of things so sorry for such a late response.
But latest release resolves that problem.
